CREATE TABLE [dbo].[Users]
(
	Id INT IDENTITY(1, 1) NOT NULL,
	Username NVARCHAR(32) NOT NULL,
	Password NVARCHAR(200) NOT NULL,
	IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
	CreatedOn DATETIME NOT NULL CONSTRAINT DF_Users_CreatedOn DEFAULT (GETDATE()),
	LastLogin DATETIME NOT NULL CONSTRAINT DF_Users_LastLogin DEFAULT(GETDATE()),
	CONSTRAINT PK_Users PRIMARY KEY (Id),
	CONSTRAINT UQ_Users_Username UNIQUE (Username)
)
GO

CREATE UNIQUE INDEX UX_Users_Username ON Users(Username) INCLUDE (Password, IsActive)
GO